version: '3.8'

services:
  jupyter:
    build:
      context: .
    container_name: rd_tattoo_notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_PASSWORD=argon2:$argon2id$v=19$m=10240,t=10,p=8$osb8JHe5sCzBbr3kwSDM9Q$00VAFlXQmkwcbWNqCFxnx9itTrTPxKAOAwE199b2fFI
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    networks:
      - rd_tattoo_network

networks:
  rd_tattoo_network:
    driver: bridge 